import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";

export const users = [
  {
    _id: uuid(),
    firstName: "Abhishek",
    lastName: "Shah",
    username: "Abhishek1601",
    password: "Abhishek123",
    profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289356/57854_ng7chz.jpg",
    bio: "Hey! Abhishek here",
    website: "",
    bookmarks: [],
    followers: [
      {
        _id: uuid(),
        firstName: "Emily",
        lastName: "Turner",
        username: "emily1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290014/39547_kmyvnn.jpg",
      },
      {
        _id: uuid(),
        firstName: "Benjamin",
        lastName: "Hayes",
        username: "benjamin1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289094/60111_oliiv2.jpg",
      },
      {
        _id: uuid(),
        firstName: "Olivia",
        lastName: "Garcia",
        username: "olivia1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289987/39550_ib1rq9.jpg",
      },
    ],
    following: [
      {
        _id: uuid(),
        firstName: "Ava",
        lastName: "Patel",
        username: "ava1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289969/39548_vclqqg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Caleb",
        lastName: "Reynolds",
        username: "caleb1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289188/832_ejd4g7.jpg",
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Emily",
    lastName: "Turner",
    username: "emily1601",
    password: "Emily123",
    profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290014/39547_kmyvnn.jpg",
    bio: "Hey! Emily here",
    website: "",
    bookmarks: [],
    followers: [
      {
        _id: uuid(),
        firstName: "Abhishek",
        lastName: "Shah",
        username: "Abhishek1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290002/Children_avatars_01Un_15_d8ahbg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Benjamin",
        lastName: "Hayes",
        username: "benjamin1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289094/60111_oliiv2.jpg",
      },
      {
        _id: uuid(),
        firstName: "Olivia",
        lastName: "Garcia",
        username: "olivia1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289987/39550_ib1rq9.jpg",
      },
    ],
    following: [
      {
        _id: uuid(),
        firstName: "Ava",
        lastName: "Patel",
        username: "ava1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289969/39548_vclqqg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Caleb",
        lastName: "Reynolds",
        username: "caleb1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289188/832_ejd4g7.jpg",
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Benjamin",
    lastName: "Hayes",
    username: "benjamin1601",
    password: "Benjamin123",
    profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289094/60111_oliiv2.jpg",
    bio: "Hey! Benjamin here",
    website: "",
    bookmarks: [],
    followers: [
      {
        _id: uuid(),
        firstName: "Emily",
        lastName: "Turner",
        username: "emily1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290014/39547_kmyvnn.jpg",
      },
      {
        _id: uuid(),
        firstName: "Abhishek",
        lastName: "Shah",
        username: "Abhishek1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290002/Children_avatars_01Un_15_d8ahbg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Olivia",
        lastName: "Garcia",
        username: "olivia1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289987/39550_ib1rq9.jpg",
      },
    ],
    following: [
      {
        _id: uuid(),
        firstName: "Ava",
        lastName: "Patel",
        username: "ava1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289969/39548_vclqqg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Caleb",
        lastName: "Reynolds",
        username: "caleb1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289188/832_ejd4g7.jpg",
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Ava",
    lastName: "Patel",
    username: "ava1601",
    password: "Ava123",
    profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289969/39548_vclqqg.jpg",
    bio: "Hey! Ava here",
    website: "",
    bookmarks: [],
    followers: [
      {
        _id: uuid(),
        firstName: "Emily",
        lastName: "Turner",
        username: "emily1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290014/39547_kmyvnn.jpg",
      },
      {
        _id: uuid(),
        firstName: "Benjamin",
        lastName: "Hayes",
        username: "benjamin1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289094/60111_oliiv2.jpg",
      },
      {
        _id: uuid(),
        firstName: "Olivia",
        lastName: "Garcia",
        username: "olivia1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289987/39550_ib1rq9.jpg",
      },
    ],
    following: [
      {
        _id: uuid(),
        firstName: "Abhishek",
        lastName: "Shah",
        username: "Abhishek1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290002/Children_avatars_01Un_15_d8ahbg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Caleb",
        lastName: "Reynolds",
        username: "caleb1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289188/832_ejd4g7.jpg",
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Caleb",
    lastName: "Reynolds",
    username: "caleb1601",
    password: "Caleb123",
    profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289188/832_ejd4g7.jpg",
    bio: "Hey! Caleb here",
    website: "",
    bookmarks: [],
    followers: [
      {
        _id: uuid(),
        firstName: "Emily",
        lastName: "Turner",
        username: "emily1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290014/39547_kmyvnn.jpg",
      },
      {
        _id: uuid(),
        firstName: "Benjamin",
        lastName: "Hayes",
        username: "benjamin1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289094/60111_oliiv2.jpg",
      },
      {
        _id: uuid(),
        firstName: "Olivia",
        lastName: "Garcia",
        username: "olivia1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289987/39550_ib1rq9.jpg",
      },
    ],
    following: [
      {
        _id: uuid(),
        firstName: "Ava",
        lastName: "Patel",
        username: "ava1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289969/39548_vclqqg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Abhishek",
        lastName: "Shah",
        username: "Abhishek1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290002/Children_avatars_01Un_15_d8ahbg.jpg",
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Sophia",
    lastName: "Mitchell",
    username: "sophia1601",
    password: "Sophia123",
    profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290411/39551_xgxenv.jpg",
    bio: "Hey! Sophia here",
    website: "",
    bookmarks: [],
    followers: [
      {
        _id: uuid(),
        firstName: "Emily",
        lastName: "Turner",
        username: "emily1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290014/39547_kmyvnn.jpg",
      },
      {
        _id: uuid(),
        firstName: "Benjamin",
        lastName: "Hayes",
        username: "benjamin1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289094/60111_oliiv2.jpg",
      },
      {
        _id: uuid(),
        firstName: "Olivia",
        lastName: "Garcia",
        username: "olivia1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289987/39550_ib1rq9.jpg",
      },
    ],
    following: [
      {
        _id: uuid(),
        firstName: "Ava",
        lastName: "Patel",
        username: "ava1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289969/39548_vclqqg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Caleb",
        lastName: "Reynolds",
        username: "caleb1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289188/832_ejd4g7.jpg",
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Isaac",
    lastName: "Anderson",
    username: "isaac1601",
    password: "Isaac123",
    profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289356/57854_ng7chz.jpg",
    bio: "Hey! Isaac here",
    website: "",
    bookmarks: [],
    followers: [
      {
        _id: uuid(),
        firstName: "Emily",
        lastName: "Turner",
        username: "emily1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290014/39547_kmyvnn.jpg",
      },
      {
        _id: uuid(),
        firstName: "Benjamin",
        lastName: "Hayes",
        username: "benjamin1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289094/60111_oliiv2.jpg",
      },
      {
        _id: uuid(),
        firstName: "Olivia",
        lastName: "Garcia",
        username: "olivia1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289987/39550_ib1rq9.jpg",
      },
    ],
    following: [
      {
        _id: uuid(),
        firstName: "Ava",
        lastName: "Patel",
        username: "ava1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289969/39548_vclqqg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Caleb",
        lastName: "Reynolds",
        username: "caleb1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289188/832_ejd4g7.jpg",
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Olivia",
    lastName: "Garcia",
    username: "olivia1601",
    password: "Olivia123",
    profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289987/39550_ib1rq9.jpg",
    bio: "Hey! Olivia here",
    website: "",
    bookmarks: [],
    followers: [
      {
        _id: uuid(),
        firstName: "Emily",
        lastName: "Turner",
        username: "emily1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290014/39547_kmyvnn.jpg",
      },
      {
        _id: uuid(),
        firstName: "Benjamin",
        lastName: "Hayes",
        username: "benjamin1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289094/60111_oliiv2.jpg",
      },
      {
        _id: uuid(),
        firstName: "Abhishek",
        lastName: "Shah",
        username: "Abhishek1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290002/Children_avatars_01Un_15_d8ahbg.jpg",
      },
    ],
    following: [
      {
        _id: uuid(),
        firstName: "Ava",
        lastName: "Patel",
        username: "ava1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289969/39548_vclqqg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Caleb",
        lastName: "Reynolds",
        username: "caleb1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289188/832_ejd4g7.jpg",
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Elijah",
    lastName: "Wright",
    username: "elijah1601",
    password: "Elijah123",
    profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289464/828_etzai0.jpg",
    bio: "Hey! Elijah here",
    website: "",
    bookmarks: [],
    followers: [
      {
        _id: uuid(),
        firstName: "Emily",
        lastName: "Turner",
        username: "emily1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687290014/39547_kmyvnn.jpg",
      },
      {
        _id: uuid(),
        firstName: "Benjamin",
        lastName: "Hayes",
        username: "benjamin1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289094/60111_oliiv2.jpg",
      },
      {
        _id: uuid(),
        firstName: "Olivia",
        lastName: "Garcia",
        username: "olivia1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289987/39550_ib1rq9.jpg",
      },
    ],
    following: [
      {
        _id: uuid(),
        firstName: "Ava",
        lastName: "Patel",
        username: "ava1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289969/39548_vclqqg.jpg",
      },
      {
        _id: uuid(),
        firstName: "Caleb",
        lastName: "Reynolds",
        username: "caleb1601",
        profileAvatar: "https://res.cloudinary.com/dnagcmyka/image/upload/v1687289188/832_ejd4g7.jpg",
      },
    ],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];